// <auto-generated />
namespace ClinicalKnowledgeManager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RenameCodeSetToCodeSystem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameCodeSetToCodeSystem));
        
        string IMigrationMetadata.Id
        {
            get { return "201302151729392_RenameCodeSetToCodeSystem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
